### ISSUE TITLE
Make cookie path configurable

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/google-analytics-beacon-net#1]
### Motivation

The cookie [`path`](https://github.com/Kentico/google-analytics-beacon-net/blob/master/GaBeacon/Controllers/BeaconController.cs#L24) attribute is currently hard-coded.

### Design guidelines

Make it configurable externally, via environment variables.

**Comment by nxnfufunezn** [comment]
this seems like good issue to get me started

**Comment by petrsvihlik** [comment]
I've just sent you an invitation to the project. If you accept it, I'll be able to assign the issue to you.

**Comment by nxnfufunezn** [comment]
accepted
