### ISSUE TITLE
Use different method of random number generation

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/google-analytics-beacon-net#3]
### Motivation

The [original project](https://github.com/igrigorik/ga-beacon) uses a [CSPRNG](https://golang.org/pkg/crypto/rand/) to generate the UUID.

### Design guidelines

Consider using .NET's [RandomNumberGenerator](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator.create).

**Comment by petrsvihlik** [comment]
closing because of #7 

@JanLenoch please make sure you close the issues when they're not relevant anymore. thx
